"""Add is_active and manager_id to users

Revision ID: 16d34f2baf40
Revises: 001_initial
Create Date: 2026-09-29 20:13:18.236598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16d34f2baf40'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tenants_short_code_key', 'tenants', type_='unique')
    op.create_index(op.f('ix_tenants_short_code'), 'tenants', ['short_code'], unique=True)
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('users', sa.Column('manager_id', sa.UUID(), nullable=True))
    op.drop_index('idx_users_tenant_id', table_name='users')
    op.drop_constraint('users_tenant_id_email_key', 'users', type_='unique')
    op.create_unique_constraint('uq_user_email_per_tenant', 'users', ['tenant_id', 'email'])
    op.create_foreign_key(None, 'users', 'users', ['manager_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint('uq_user_email_per_tenant', 'users', type_='unique')
    op.create_unique_constraint('users_tenant_id_email_key', 'users', ['tenant_id', 'email'])
    op.create_index('idx_users_tenant_id', 'users', ['tenant_id'], unique=False)
    op.drop_column('users', 'manager_id')
    op.drop_column('users', 'is_active')
    op.drop_index(op.f('ix_tenants_short_code'), table_name='tenants')
    op.create_unique_constraint('tenants_short_code_key', 'tenants', ['short_code'])
    # ### end Alembic commands ###
